namespace: test

image:
  repository: nexus.nomad.local/docker-hosted/fastapi1
  tag: myid3
  pullPolicy: Always

replicaCount: 1

service:
  type: ClusterIP
  port: 8000

imagePullSecrets:
  - name: nexus-registry-secret

env:
  CURRENT_ENV_VAR: some-test-data

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: fastapi2.nomad.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
